In [1]:
import pandas as pd 

df = pd.read_csv('Open311_20251007.csv')

In [2]:
df.columns

Index(['service_request_id', 'requested_datetime', 'updated_datetime',
       'closed_date', 'status_description', 'source', 'service_name',
       'description', 'agency_responsible', 'address', 'city', 'state', 'zip',
       'lat', 'long', 'Georeference', 'SLA Days', 'Request Complete Days',
       'SLA DIff Days'],
      dtype='object')

In [3]:
df.head(10)

,service_request_id,requested_datetime,updated_datetime,closed_date,status_description,source,service_name,description,agency_responsible,address,city,state,zip,lat,long,Georeference,SLA Days,Request Complete Days,SLA DIff Days
0,523,06/21/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/21/2011 04:00:00 AM,closed,NaN,Trash,Bags/cans must have sticker attached. 950,NaN,431 VILLAGE,Bloomington,IN,NaN,NaN,NaN,NaN,9.0,0.0,-9.0
1,470,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Recycling,Recycables and non-recycables waste mixed. 949,NaN,1105 S Washington ST,Bloomington,IN,47401.0,39.153980,-86.532249,POINT (-86.53224945 39.15398026),NaN,0.0,NaN
2,471,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Exceeds weight Limit of 40 pounds.,NaN,620 S Lincoln ST,Bloomington,IN,47401.0,39.158478,-86.531494,POINT (-86.53149414 39.15847778),9.0,0.0,-9.0
3,472,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Bags/cans must have sticker attached. 956,NaN,1835 S Maxwell ST,Bloomington,IN,47401.0,39.145115,-86.514412,POINT (-86.51441193 39.1451149),9.0,0.0,-9.0
4,473,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Exceeds weight Limit of 40 pounds. Cans over ...,NaN,1019 E Miller DR,Bloomington,IN,47401.0,39.147038,-86.519875,POINT (-86.51987457 39.14703751),9.0,0.0,-9.0
5,474,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Exceeds weight Limit of 40 pounds. 948,NaN,3827 S Laura WAY,Bloomington,IN,47401.0,39.126755,-86.518715,POINT (-86.5187149 39.12675476),9.0,0.0,-9.0
6,475,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Exceeds weight Limit of 40 pounds. 948,NaN,3706 S Bainbridge DR,Bloomington,IN,47401.0,39.129047,-86.519623,POINT (-86.5196228 39.12904739),9.0,0.0,-9.0
7,476,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Exceeds weight Limit of 40 pounds.,NaN,1815 E Atwater AVE,Bloomington,IN,47401.0,39.163280,-86.511383,POINT (-86.51138306 39.16328049),9.0,0.0,-9.0
8,477,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,06/27/2011 04:00:00 AM,closed,NaN,Trash,Bags/cans must have sticker attached.,NaN,405 BALLENTINE,Bloomington,IN,NaN,NaN,NaN,NaN,9.0,0.0,-9.0
9,478,06/27/2011 04:00:00 AM,09/11/2016 10:02:05 PM,08/22/2011 03:03:28 PM,closed,NaN,Recycling,Recycable items not properly sorted. 946,NaN,516 S Washington ST,Bloomington,IN,47401.0,39.160286,-86.532593,POINT (-86.53259277 39.16028595),NaN,56.0,NaN

In [4]:
df.isna().sum()

service_request_id           0
requested_datetime           0
updated_datetime             0
closed_date                218
status_description           0
source                   34340
service_name                 0
description               9203
agency_responsible       75504
address                  11268
city                        59
state                       59
zip                      33647
lat                      23888
long                     23886
Georeference             23888
SLA Days                 59308
Request Complete Days      218
SLA DIff Days            59366
dtype: int64

In [5]:
#step 1: replace City and state for NAN values 
df['city'] = df['city'].fillna('Bloomington')
df['state'] = df['state'].fillna('IN')

In [6]:
#step 2: drop the columns Georeference , SLA Days , Request Complete Days , SLA Diff days 
cols_to_drop = [
    'Request Complete Days',
    'SLA DIff Days',
    'SLA Days',
    'Georeference'
]

df = df.drop(columns=cols_to_drop)

In [7]:
#Step 3: Replacing NAN values for source to "Source Unknown"
df['source'] = df['source'].fillna('Source Unknown')

In [8]:
import re

# Extract ZIPs 
df['zip_from_address'] = df['address'].apply(
    lambda x: re.search(r'\b4\d{4}\b', str(x)).group(0) if re.search(r'\b4\d{4}\b', str(x)) else None
)

# Filter rows where a valid Bloomington ZIP was found
zip_found = df[df['zip_from_address'].notna()]

#print first 20 rows
print(zip_found[['address', 'zip_from_address']].head(20))

                                                 address zip_from_address
83332                                              47403            47403
84850                                              47401            47401
85007                                              47401            47401
86086                                              47401            47401
88375                                              47403            47403
88775                                              47401            47401
88776                                              47401            47401
90605  1269 W Countryside Ln, Bloomington, Indiana, 4...            47403
90958      300-498 W 8th St, Bloomington, Indiana, 47404            47404
92778      300-498 W 8th St, Bloomington, Indiana, 47404            47404
92780  400-598 W Northlane Dr, Bloomington, Indiana, ...            47404
92785  Knightridge Apartments, Bloomington, Indiana, ...            47401
92789               IN-48 W, Bloomington, Indiana, 47404            47404
92790    117-199 S Union St, Bloomington, Indiana, 47408            47408
92791  1300-1498 N Arlington Park Dr, Bloomington, In...            47404
92795   2800-2998 N Prow Rd, Bloomington, Indiana, 47404            47404
92797   2801-2899 N Dunn St, Bloomington, Indiana, 47408            47408
92798   501-599 N Morton St, Bloomington, Indiana, 47404            47404
92801   1892-1898 E 10th St, Bloomington, Indiana, 47406            47406
92805                        47404, Bloomington, Indiana            47404

In [9]:
num_zip_found = df['zip_from_address'].notna().sum()
print(num_zip_found)

4146

In [10]:
num_non_nan_zip = df['zip'].notna().sum()
print(num_non_nan_zip)

88601

In [11]:
#Step 4 : adding the zip codes extracted from address to ZIP and storing 00000 for unknown zip codes

df['zip'] = df['zip'].fillna(df['zip_from_address'])
df['zip'] = df['zip'].fillna("00000")
df = df.drop(columns=['zip_from_address'])

In [12]:
#Step 5: Replacing NAN values for agency to "Agency responsible not mentioned"
df['agency_responsible'] = df['agency_responsible'].fillna('Agency responsible not mentioned')

In [13]:
df.isna().sum()

service_request_id        0
requested_datetime        0
updated_datetime          0
closed_date             218
status_description        0
source                    0
service_name              0
description            9203
agency_responsible        0
address               11268
city                      0
state                     0
zip                       0
lat                   23888
long                  23886
dtype: int64

In [14]:
zip_category_map = {
    47401: "Downtown",
    47403: "Industrial",
    47408: "Industrial",
    47402: "Residential",
    47404: "Residential",
    47405: "Suburban Towns",
    47426: "Suburban Towns",
    47429: "Suburban Towns",
    47433: "Suburban Towns",
    47441: "Suburban Towns",
    47448: "Suburban Towns",
    47452: "Suburban Towns",
    47458: "Suburban Towns",
    47459: "Suburban Towns",
    47460: "Suburban Towns",
    47421: "Rural Towns",
    47406: "Rural Towns",
    47462: "Rural Towns"
}

# Ensure ZIPs are numeric
df['zip'] = pd.to_numeric(df['zip'], errors='coerce')

# Map ZIP to category
df['area_category'] = df['zip'].map(zip_category_map)

# Fill anything not mapped as "Out of Area"
df['area_category'] = df['area_category'].fillna("Out of Area")

In [15]:
# creating a smaller data frame 
df['updated_datetime'] = pd.to_datetime(df['updated_datetime'], errors='coerce')

df_small = df[
    (df['updated_datetime'].dt.year >= 2020) &
    (df['updated_datetime'].dt.year <= 2025)
].copy()

/var/folders/k6/jyr0s9vd7nv11z2pg1m93l240000gn/T/ipykernel_49552/1736931091.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['updated_datetime'] = pd.to_datetime(df['updated_datetime'], errors='coerce')

In [16]:
df_small.shape

(43391, 16)

In [17]:
df_small.head(10)

,service_request_id,requested_datetime,updated_datetime,closed_date,status_description,source,service_name,description,agency_responsible,address,city,state,zip,lat,long,area_category
142,620,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial
143,621,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass.,Agency responsible not mentioned,1401 W Woodhill DR,Bloomington,IN,47403.0,39.156933,-86.548393,Industrial
144,622,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Blocked Street,bushes and weeds overgrown on west side of street,Agency responsible not mentioned,704 W Ralston DR,Bloomington,IN,47403.0,39.138622,-86.541130,Industrial
145,623,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Trash,"Trash in yard and driveway - 20 bags of trash,...",HAND,3711 N Kinser PIKE,Bloomington,IN,47404.0,39.200760,-86.545341,Residential
194,684,06/08/2011 04:00:00 AM,2020-10-05 14:42:52,06/08/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial
218,791,05/31/2011 04:00:00 AM,2020-10-05 14:42:52,05/31/2011 04:00:00 AM,closed,Phone Call,Trash,The grass is very tall espically in the back y...,HAND,3351 N Kinser PIKE,Bloomington,IN,47404.0,39.197865,-86.542358,Residential
258,1057,05/10/2011 04:00:00 AM,2020-10-05 14:42:52,05/10/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,816 S Larkspur LN,Bloomington,IN,47403.0,39.157402,-86.547607,Industrial
290,1277,04/25/2011 04:00:00 AM,2020-10-05 14:42:52,04/25/2011 04:00:00 AM,closed,Phone Call,Trash,Trash in the back yard.,Agency responsible not mentioned,1205 S Madison ST,Bloomington,IN,47403.0,39.153015,-86.537460,Industrial
377,4395,09/10/2010 04:00:00 AM,2020-10-05 14:42:52,09/10/2010 04:00:00 AM,closed,Phone Call,Trash,lots of trash and debris scattered around prop...,Agency responsible not mentioned,3073 E Amy LN,Bloomington,IN,47408.0,39.169224,-86.496773,Industrial
406,4509,09/07/2010 04:00:00 AM,2020-10-05 14:42:52,09/07/2010 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Engineering,111 E Cottage Grove AVE,Bloomington,IN,47408.0,39.172661,-86.532822,Industrial

In [18]:
#step 1: replace City and state for NAN values
df_small['city'] = df['city'].fillna('Bloomington')
df_small['state'] = df['state'].fillna('IN')

In [19]:
import re

# Extract ZIPs
df_small['zip_from_address'] = df_small['address'].apply(
    lambda x: re.search(r'\b4\d{4}\b', str(x)).group(0) if re.search(r'\b4\d{4}\b', str(x)) else None
)

# Filter rows where a valid Bloomington ZIP was found
zip_found = df_small[df_small['zip_from_address'].notna()]

#print first 20 rows
print(zip_found[['address', 'zip_from_address']].head(20))

                                                 address zip_from_address
83332                                              47403            47403
92791  1300-1498 N Arlington Park Dr, Bloomington, In...            47404
92797   2801-2899 N Dunn St, Bloomington, Indiana, 47408            47408
92817  2217-2599 E Rhorer Rd, Bloomington, Indiana, 4...            47401
92849     701-799 W 13th St, Bloomington, Indiana, 47404            47404
92918  3301-3999 W Jonathan Dr, Bloomington, Indiana,...            47404
92947  401-499 E Kirkwood Ave, Bloomington, Indiana, ...            47408
92949      300-398 W 7th St, Bloomington, Indiana, 47404            47404
92952  2000-2098 E Maxwell Ln, Bloomington, Indiana, ...            47401
92969  2700-2898 E Blue Ridge Dr, Bloomington, Indian...            47408
92991  1010-1298 W Country Club Dr, Bloomington, Indi...            47403
92995   2119-2121 S High St, Bloomington, Indiana, 47401            47401
93015     1-109 N Walnut St, Bloomington, Indiana, 47404            47404
93026      1722 N Walnut St, Bloomington, Indiana, 47404            47404
93051       201 S Walnut St, Bloomington, Indiana, 47404            47404
93123  1616-1638 S Henderson St, Bloomington, Indiana...            47401
93129   401-499 N Morton St, Bloomington, Indiana, 47404            47404
93148         715 E 11th St, Bloomington, Indiana, 47408            47408
93190   1401-1411 E 10th St, Bloomington, Indiana, 47408            47408
93195                        47401, Bloomington, Indiana            47401

In [20]:
num_zip_found = df_small['zip_from_address'].notna().sum()
print(num_zip_found)

3043

In [21]:
#Step 4 : adding the zip codes extracted from address to ZIP and storing 00000 for unknown zip codes

df_small['zip'] = df_small['zip'].fillna(df_small['zip_from_address'])
df_small['zip'] = df_small['zip'].fillna("00000")
df_small = df_small.drop(columns=['zip_from_address'])

In [22]:
#Step 5: Replacing NAN values for agency to "Agency responsible not mentioned"
df_small['agency_responsible'] = df_small['agency_responsible'].fillna('Agency responsible not mentioned')

In [23]:
zip_category_map = {
    47401: "Downtown/IU Campus",
    47403: "Industrial",
    47408: "Industrial",
    47402: "Residential",
    47404: "Residential",
    47405: "Suburban Towns",
    47426: "Suburban Towns",
    47429: "Suburban Towns",
    47433: "Suburban Towns",
    47441: "Suburban Towns",
    47448: "Suburban Towns",
    47452: "Suburban Towns",
    47458: "Suburban Towns",
    47459: "Suburban Towns",
    47460: "Suburban Towns",
    47421: "Rural Towns",
    47406: "Rural Towns",
    47462: "Rural Towns"
}

# Ensure ZIPs are numeric
df_small['zip'] = pd.to_numeric(df_small['zip'], errors='coerce')

# Map ZIP to category
df_small['area_category'] = df_small['zip'].map(zip_category_map)

# Fill anything not mapped as "Out of Area"
df_small['area_category'] = df_small['area_category'].fillna("Out of Area")

In [24]:
#Step 3: Replacing NAN values for source to "Source Unknown"
df_small['source'] = df_small['source'].fillna('Source Unknown')

In [25]:
df_small.head(10)

,service_request_id,requested_datetime,updated_datetime,closed_date,status_description,source,service_name,description,agency_responsible,address,city,state,zip,lat,long,area_category
142,620,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial
143,621,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass.,Agency responsible not mentioned,1401 W Woodhill DR,Bloomington,IN,47403.0,39.156933,-86.548393,Industrial
144,622,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Blocked Street,bushes and weeds overgrown on west side of street,Agency responsible not mentioned,704 W Ralston DR,Bloomington,IN,47403.0,39.138622,-86.541130,Industrial
145,623,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Trash,"Trash in yard and driveway - 20 bags of trash,...",HAND,3711 N Kinser PIKE,Bloomington,IN,47404.0,39.200760,-86.545341,Residential
194,684,06/08/2011 04:00:00 AM,2020-10-05 14:42:52,06/08/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial
218,791,05/31/2011 04:00:00 AM,2020-10-05 14:42:52,05/31/2011 04:00:00 AM,closed,Phone Call,Trash,The grass is very tall espically in the back y...,HAND,3351 N Kinser PIKE,Bloomington,IN,47404.0,39.197865,-86.542358,Residential
258,1057,05/10/2011 04:00:00 AM,2020-10-05 14:42:52,05/10/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,816 S Larkspur LN,Bloomington,IN,47403.0,39.157402,-86.547607,Industrial
290,1277,04/25/2011 04:00:00 AM,2020-10-05 14:42:52,04/25/2011 04:00:00 AM,closed,Phone Call,Trash,Trash in the back yard.,Agency responsible not mentioned,1205 S Madison ST,Bloomington,IN,47403.0,39.153015,-86.537460,Industrial
377,4395,09/10/2010 04:00:00 AM,2020-10-05 14:42:52,09/10/2010 04:00:00 AM,closed,Phone Call,Trash,lots of trash and debris scattered around prop...,Agency responsible not mentioned,3073 E Amy LN,Bloomington,IN,47408.0,39.169224,-86.496773,Industrial
406,4509,09/07/2010 04:00:00 AM,2020-10-05 14:42:52,09/07/2010 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Engineering,111 E Cottage Grove AVE,Bloomington,IN,47408.0,39.172661,-86.532822,Industrial

In [80]:
df_small.isna().sum()

service_request_id          0
requested_datetime          0
updated_datetime            0
closed_date               213
status_description          0
source                      0
service_name                0
description              7040
agency_responsible          0
address                  6014
city                        0
state                       0
zip                         0
lat                      7013
long                     7013
area_category               0
service_category            0
season                      0
service_category_code       0
dtype: int64

In [26]:
#unique services from 2020 - 2025 
unique_service = df_small['service_name'].unique()
print(unique_service)

['Excessive Growth' 'Blocked Street' 'Trash'
 'Sewer Problems (Sanitary Sewers)' 'Parking on Unimproved Surface'
 'Temporary Signage w/o permit' 'Unsafe Buildings' 'Other' 'Line of Sight'
 'Traffic Related Complaints' 'Street Snow Removal' 'Yard Waste'
 'Recycling' 'Water Utility Billing Problems' 'Sidewalk Snow Removal'
 'Water Quality' 'Water Utility Problems' 'Sidewalk & Curb Complaints'
 'City Construction Projects' 'Potholes, Other Street Repair'
 'Fire Hazards' 'City Performance' 'Animal Control & Neglected Pets'
 'Graffiti' 'Abandoned Vehicle' 'Parking Permits'
 'Debris Removal (Sand, General Street Debris)'
 'Sewer Problems (Storm Sewers)' 'Utilities Construction' 'Street Lights'
 'Traffic Suggestions' 'Trails' 'Biking & Walking' 'Traffic Signals'
 'Website & Web Services Feedback' 'Leaf Collection'
 'Parking Meters and Citations' 'Bus Services (Bloomington Transit)'
 'Parks & Playgrounds' 'Parks & Rec Buildings' 'Parks & Rec Programs'
 'Inaccessible Parking' 'Drainage or Runoff' 'Sidewalk Requests'
 'Blocked Sidewalk' 'Utilities Yardwork' 'Accessibility Problem'
 'Business' 'Crow Sightings' 'Smoking Violation'
 'Scooters, Bike-share and Related Issues' 'Street & Traffic Signs'
 'Report issues with Lime scooters' 'Report issues with BIRD scooters'
 'Food Truck Issues' 'Illicit Discharge (Storm Sewers)' 'Taxi Complaints'
 'Street Trees' 'Wildlife Conflict' 'Parking Garages'
 'Utility Construction Projects' 'Request a new Street Light'
 'Nuisance Lights' 'Report issues with Veo Scooters' 'GIS Issue']

In [27]:
unique_agency = df_small['agency_responsible'].unique()
print(unique_agency)

['Agency responsible not mentioned' 'HAND' 'Engineering'
 'Utilities Engineering' 'Police Department' 'Public Works Department'
 'Animal Control' 'Street Department' 'Parking Services'
 'Information and Technology Services' 'Facilities'
 'Utilities Meter Services' 'Utilities T & D' 'Sanitation Department'
 'Parks and Recreation' 'Planning and Transportation' 'Legal Department'
 'Utilities Environmental' 'Community and Family Resources' 'City Clerk'
 'Mobility' 'Economic Development' 'Utilities Customer Service'
 'Fire Department' 'Transit' 'Risk Department' "Mayor's Office"
 'Utilities Administration' 'Human Resources' 'Utilities Finance'
 'Controllers Office' 'Council Office']

In [29]:
service_categories = {
    # Environmental Issues
    "Excessive Growth": "Environmental Issues",
    "Trash": "Environmental Issues",
    "Yard Waste": "Environmental Issues",
    "Recycling": "Environmental Issues",
    "Leaf Collection": "Environmental Issues",
    "Drainage or Runoff": "Environmental Issues",
    "Street Snow Removal": "Environmental Issues",  # fixed typo
    "Sidewalk Snow Removal": "Environmental Issues",
    "Debris Removal (Sand, General Street Debris)": "Environmental Issues",
    "Illicit Discharge (Storm Sewers)": "Environmental Issues",
    "Sewer Problems (Storm Sewers)": "Environmental Issues",
    "Sewer Problems (Sanitary Sewers)": "Environmental Issues",
    "Water Quality": "Environmental Issues",
    "Water Utility Problems": "Environmental Issues",
    "Street Trees": "Environmental Issues",
    "Trails": "Environmental Issues",
    "Parks & Playgrounds": "Environmental Issues",
    "Parks & Rec Buildings": "Environmental Issues",
    "Parks & Rec Programs": "Environmental Issues",
    "Wildlife Conflict": "Environmental Issues",

    # Transportation and Street Operations
    "Blocked Street": "Transportation and Street Operations",
    "Line of Sight": "Transportation and Street Operations",
    "Traffic Related Complaints": "Transportation and Street Operations",
    "Potholes, Other Street Repair": "Transportation and Street Operations",
    "Traffic Suggestions": "Transportation and Street Operations",
    "Traffic Signals": "Transportation and Street Operations",
    "Street Lights": "Transportation and Street Operations",
    "Street & Traffic Signs": "Transportation and Street Operations",
    "Blocked Sidewalk": "Transportation and Street Operations",
    "Sidewalk Requests": "Transportation and Street Operations",
    "Sidewalk & Curb Complaints": "Transportation and Street Operations",
    "Request a new Street Light": "Transportation and Street Operations",
    "Inaccessible Parking": "Transportation and Street Operations",
    "Parking on Unimproved Surface": "Transportation and Street Operations",
    "Parking Permits": "Transportation and Street Operations",
    "Parking Meters and Citations": "Transportation and Street Operations",
    "Parking Garages": "Transportation and Street Operations",
    "Biking & Walking": "Transportation and Street Operations",

    # Utilities (Billing, Metering, Admin)
    "Water Utility Billing Problems": "Utilities",
    "Utilities Meter Services": "Utilities",
    "Utilities T & D": "Utilities",
    "Utilities Yardwork": "Utilities",
    "Utilities Environmental": "Utilities",
    "Utilities Customer Service": "Utilities",
    "Utilities Administration": "Utilities",
    "Utilities Finance": "Utilities",

    # Construction & City Infrastructure
    "City Construction Projects": "Construction & Infrastructure",
    "Utilities Construction": "Construction & Infrastructure",
    "Utility Construction Projects": "Construction & Infrastructure",
    "Temporary Signage w/o permit": "Construction & Infrastructure",
    "Unsafe Buildings": "Construction & Infrastructure",
    "Business": "Construction & Infrastructure",

    # Public Safety & Ordinance Enforcement
    "Animal Control & Neglected Pets": "Public Safety",
    "Fire Hazards": "Public Safety",
    "Abandoned Vehicle": "Public Safety",
    "Crow Sightings": "Public Safety",
    "Smoking Violation": "Public Safety",
    "Taxi Complaints": "Public Safety",

    # City Services & Administrative Support
    "Other": "City Services & Administrative",
    "City Performance": "City Services & Administrative",
    "Website & Web Services Feedback": "City Services & Administrative",
    "Accessibility Problem": "City Services & Administrative",
    "Scooters, Bike-share and Related Issues": "City Services & Administrative",
    "Report issues with Lime scooters": "City Services & Administrative",
    "Report issues with BIRD scooters": "City Services & Administrative",
    "Report issues with Veo Scooters": "City Services & Administrative",
    "Bus Services (Bloomington Transit)": "City Services & Administrative",
    "GIS Issue": "City Services & Administrative",
}

# Map service_name to service_category safely
df_small['service_category'] = df_small['service_name'].map(service_categories)

In [30]:
df_small.head(10)

,service_request_id,requested_datetime,updated_datetime,closed_date,status_description,source,service_name,description,agency_responsible,address,city,state,zip,lat,long,area_category,service_category
142,620,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial,Environmental Issues
143,621,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,Tall grass.,Agency responsible not mentioned,1401 W Woodhill DR,Bloomington,IN,47403.0,39.156933,-86.548393,Industrial,Environmental Issues
144,622,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Blocked Street,bushes and weeds overgrown on west side of street,Agency responsible not mentioned,704 W Ralston DR,Bloomington,IN,47403.0,39.138622,-86.541130,Industrial,Transportation and Street Operations
145,623,06/13/2011 04:00:00 AM,2020-10-05 14:42:52,06/13/2011 04:00:00 AM,closed,Phone Call,Trash,"Trash in yard and driveway - 20 bags of trash,...",HAND,3711 N Kinser PIKE,Bloomington,IN,47404.0,39.200760,-86.545341,Residential,Environmental Issues
194,684,06/08/2011 04:00:00 AM,2020-10-05 14:42:52,06/08/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,1301 W Woodhill DR,Bloomington,IN,47403.0,39.157001,-86.547485,Industrial,Environmental Issues
218,791,05/31/2011 04:00:00 AM,2020-10-05 14:42:52,05/31/2011 04:00:00 AM,closed,Phone Call,Trash,The grass is very tall espically in the back y...,HAND,3351 N Kinser PIKE,Bloomington,IN,47404.0,39.197865,-86.542358,Residential,Environmental Issues
258,1057,05/10/2011 04:00:00 AM,2020-10-05 14:42:52,05/10/2011 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Agency responsible not mentioned,816 S Larkspur LN,Bloomington,IN,47403.0,39.157402,-86.547607,Industrial,Environmental Issues
290,1277,04/25/2011 04:00:00 AM,2020-10-05 14:42:52,04/25/2011 04:00:00 AM,closed,Phone Call,Trash,Trash in the back yard.,Agency responsible not mentioned,1205 S Madison ST,Bloomington,IN,47403.0,39.153015,-86.537460,Industrial,Environmental Issues
377,4395,09/10/2010 04:00:00 AM,2020-10-05 14:42:52,09/10/2010 04:00:00 AM,closed,Phone Call,Trash,lots of trash and debris scattered around prop...,Agency responsible not mentioned,3073 E Amy LN,Bloomington,IN,47408.0,39.169224,-86.496773,Industrial,Environmental Issues
406,4509,09/07/2010 04:00:00 AM,2020-10-05 14:42:52,09/07/2010 04:00:00 AM,closed,Phone Call,Excessive Growth,NaN,Engineering,111 E Cottage Grove AVE,Bloomington,IN,47408.0,39.172661,-86.532822,Industrial,Environmental Issues

In [31]:
missing_services = df_small.loc[~df_small['service_name'].isin(service_categories.keys()), 'service_name'].unique()
print(missing_services)

['Graffiti' 'Food Truck Issues' 'Nuisance Lights']

In [32]:
# List of missing service names
missing_services = ['Graffiti', 'Food Truck Issues', 'Nuisance Lights']

# Fill their service_category with "City Services & Administrative"
df_small.loc[df_small['service_name'].isin(missing_services), 'service_category'] = "City Services & Administrative"

In [33]:
unique_category = df_small['service_category'].unique()
print(unique_category)

['Environmental Issues' 'Transportation and Street Operations'
 'Construction & Infrastructure' 'City Services & Administrative'
 'Utilities' 'Public Safety']

In [77]:
##alternative 
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio

# ---------------------------
# Global configuration
# ---------------------------
pio.renderers.default = "notebook"

GLOBAL_FONT = "Inter, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif"
BG_COLOR = "#f0f2f5"
TEXT_COLOR = "#1a202c"
SUB_TEXT_COLOR = "#718096"

AREA_STYLE = {
    "Out of Area":        "#0077BB",  # Clear blue
    "Industrial":         "#CC3311",  # Vermillion red
    "Downtown/IU Campus": "#332288",  # Indigo
    "Residential":        "#EE7733",  # Orange
    "Suburban Towns":     "#AA3377",  # Magenta
    "Rural Towns":        "#DDCC77"   # Sand/tan
}

SERVICE_CATEGORY_COLORS = {
    "Environmental Issues":          "#117733",  # Green
    "Construction & Infrastructure": "#DDAA33",  # Gold
    "Public Safety":                 "#CC3311",  # Vermillion
    "City Services & Administrative":"#AA3377",  # Magenta
    "Transportation and Street Operations": "#0077BB",  # Clear blue
    "Utilities":                     "#332288"   # Indigo
}

seasons = ['Winter', 'Spring', 'Summer', 'Fall']

# ---------------------------
# Example Data Preparation
# ---------------------------
# Ensure df_small exists and has these columns: 'service_category', 'area_category', 'service_name', 'updated_datetime'
df_small['service_category'] = df_small['service_category'].replace({
    'Environment Issuess': 'Environmental Issues'
})
df_small['updated_datetime'] = pd.to_datetime(df_small['updated_datetime'])

# Extract season
def get_season(date):
    month = date.month
    if month in [12,1,2]: return 'Winter'
    elif month in [3,4,5]: return 'Spring'
    elif month in [6,7,8]: return 'Summer'
    else: return 'Fall'

df_small['season'] = df_small['updated_datetime'].apply(get_season)

# Encode service categories for Parcats color
df_small['service_category_code'] = df_small['service_category'].map(
    lambda x: list(SERVICE_CATEGORY_COLORS.keys()).index(x) if x in SERVICE_CATEGORY_COLORS else -1
)

# ---------------------------
# Helper functions
# ---------------------------
def get_area_color(name): 
    return AREA_STYLE.get(name, "#a0aec0")

def get_cat_color(name): 
    return SERVICE_CATEGORY_COLORS.get(name, "#cbd5e0")

def get_sunburst_data(df, season):
    df_s = df[df['season']==season]
    df_grouped = df_s.groupby(['area_category','service_category']).size().reset_index(name='count')
    ids, labels, parents, values, colors = [], [], [], [], []

    # Inner ring (area)
    area_stats = df_grouped.groupby('area_category')['count'].sum().reset_index()
    for _, row in area_stats.iterrows():
        area = row['area_category']
        ids.append(f"{season}-{area}")
        labels.append(area)
        parents.append("")
        values.append(row['count'])
        colors.append(get_area_color(area))

    # Outer ring (category)
    for _, row in df_grouped.iterrows():
        area, cat = row['area_category'], row['service_category']
        ids.append(f"{season}-{area}-{cat}")
        labels.append(cat)
        parents.append(f"{season}-{area}")
        values.append(row['count'])
        colors.append(get_cat_color(cat))

    return ids, labels, parents, values, colors

def get_parcat_data(df, season):
    df_s = df[df['season']==season]
    # Use these as dimensions: Area -> Category -> Service
    dims = [
        dict(label="Area", values=df_s['area_category'].tolist()),
        dict(label="Category", values=df_s['service_category'].tolist()),
        dict(label="Service", values=df_s['service_name'].tolist())
    ]
    return dims

# ---------------------------
# Build Figure
# ---------------------------
fig = make_subplots(
    rows=1, cols=2,
    column_widths=[0.45,0.55],
    specs=[[{"type":"sunburst"},{"type":"parcats"}]],
    subplot_titles=("Quality of Life by Area & Category","Request Flow by Service")
)

# Add traces for each season (initially visible only for first)
for i, season in enumerate(seasons):
    # Sunburst
    sb_ids, sb_lbls, sb_pars, sb_vals, sb_cols = get_sunburst_data(df_small, season)
    fig.add_trace(
        go.Sunburst(
            ids=sb_ids,
            labels=sb_lbls,
            parents=sb_pars,
            values=sb_vals,
            branchvalues="total",
            marker=dict(colors=sb_cols, line=dict(color='white', width=1.5)),
            textinfo="label+percent parent",
            hoverinfo="label+percent parent",
            name=season,
            visible=(i==0)
        ),
        row=1, col=1
    )

    # Parcats
    parcat_dims = get_parcat_data(df_small, season)
    # Line color based on service_category_code
    line_color = df_small[df_small['season']==season]['service_category_code'].tolist()
    colorscale = [[i/(len(SERVICE_CATEGORY_COLORS)-1), c] for i, c in enumerate(SERVICE_CATEGORY_COLORS.values())]

    fig.add_trace(
        go.Parcats(
            dimensions=parcat_dims,
            line=dict(color=line_color, shape="hspline", colorscale=colorscale),
            visible=(i==0)
        ),
        row=1, col=2
    )

fig.update_layout(
    annotations=[
        dict(
            text="Sunburst diagram of Distribution of service request categories across neighborhoods",
            x=0.225, y=0.95,  # slightly below the title
            xref="paper", yref="paper",
            showarrow=False,
            font=dict(size=16, color="#4a5568")
        ),
        dict(
            text="Sankey Flow from categories to specific services in Regions",
            x=0.725, y=0.95,  # slightly below the title
            xref="paper", yref="paper",
            showarrow=False,
            font=dict(size=16, color="#4a5568")
        )
    ]
)

# ---------------------------
# Dropdown for Seasons
# ---------------------------
buttons=[]
for i, season in enumerate(seasons):
    flags = [False]*(len(seasons)*2)
    flags[i*2] = True
    flags[i*2+1] = True
    buttons.append(dict(label=season, method="update", args=[{"visible":flags}]))

fig.update_layout(
    title=dict(text="<b>How do seasonal service demands impact the quality of life for Bloomington’s residents?</b>", font=dict(size=24, family=GLOBAL_FONT), x=0.5),
    updatemenus=[dict(active=0, buttons=buttons, x=0.95, y=1.12, xanchor='right', yanchor='top')],
    template="plotly_white",
    paper_bgcolor=BG_COLOR,
    plot_bgcolor=BG_COLOR,
    font=dict(family=GLOBAL_FONT, color=TEXT_COLOR),
    height=900,
    width=1500
)

# Export to HTML
fig.write_html("Bloomington_Seasonal_QoL.html")

In [78]:
import base64

with open("heatmap.png", "rb") as f:
    img_bytes = f.read()
img_b64 = base64.b64encode(img_bytes).decode()

# HTML code
heatmap_html = f'''
<div style="text-align:center; margin-top:20px;">
    <h3>Seasonal Request Distribution by Region</h3>
    <p style="font-size:14px; color:#4a5568; margin-bottom:10px;">
        This heatmap shows the number of service requests per region across different seasons.
    </p>
    <img src="data:image/png;base64,{img_b64}" alt="Heatmap" style="max-width:80%; height:auto; border:1px solid #ccc;">
</div>
'''

# Inject into your existing HTML before </body>
with open("Bloomington_Seasonal_QoL.html", "r") as f:
    html_content = f.read()

html_content = html_content.replace("</body>", heatmap_html + "\n</body>")

with open("Bloomington_dashboard_trends.html", "w") as f:
    f.write(html_content)

Dashboard edits complete! Saved as Bloomington_dashboard_trends_edited.html

In [79]:
import base64

# Paths
plotly_html = "Bloomington_dashboard_trends.html"  # existing dashboard
output_html = "Bloomington_dashboard_trends_edited.html"

# Read the HTML
with open(plotly_html, "r", encoding="utf-8") as f:
    html_content = f.read()

# --- 1. Update page <title> ---
html_content = html_content.replace(
    "<title>Plotly</title>",
    "<title>How does seasonal service demand affect Bloomington citizens’ quality of life (2020–2025)?</title>"
)

# --- 2. Prepare top section: How to read + descriptions ---
top_html = """
<div style="text-align:center; margin-top:20px; font-family:sans-serif;">
    <h2>How to read this visualization</h2>
    <p>Select a season from the dropdown. Click on any category in the sunburst or Parcats diagram to drill down further.</p>
    <p>The Sunburst Diagram and Sankey Diagram are interactive and the heatmap is static in nature.</p>
    <p>This inforgraphic shows recent 5 year data i.e. 2020 - 2025.</p>
</div>
"""

# Insert the top_html **before the first Plotly div**
split_point = html_content.find('<div id="')
html_content = html_content[:split_point] + top_html + html_content[split_point:]


# --- 4. Add dataset source link at top-right ---
source_html = """
<div style="position:fixed; top:10px; right:10px; font-size:12px; background:#fff; padding:3px; border:1px solid #ccc; z-index:999;">
    Source: <a href="https://data.bloomington.in.gov/dataset/Open311/aw6y-t4ix/about_data" target="_blank">Open311 Dataset</a>
</div>
"""
html_content = html_content.replace("</body>", source_html + "</body>")

# Save the final edited HTML
with open(output_html, "w", encoding="utf-8") as f:
    f.write(html_content)

print(f"Dashboard edits complete! Saved as {output_html}")

Dashboard edits complete! Saved as Bloomington_dashboard_trends_edited.html

In [6]:
# --- File paths ---
input_html = "Bloomington_dashboard_trends_edited.html"
output_html = "project_file_edited.html"

# --- Read the HTML file ---
with open(input_html, "r", encoding="utf-8") as f:
    html_content = f.read()

# --- Define vertical stack container for both legends on the left ---
legends_html = """
<div style="
    position:fixed;
    bottom:20px;
    left:20px;
    display:flex;
    flex-direction:column;
    gap:12px;  /* vertical space between legends */
    z-index:999;
">
  <!-- Service Legend -->
  <div style="
      background:white;
      padding:10px 14px;
      border:1px solid #ccc;
      border-radius:8px;
      font-size:13px;
      box-shadow:0 2px 6px rgba(0,0,0,0.15);
  ">
    <b>Service Categories</b><br>
    <div style="margin-top:6px;">
        <div><span style="color:#117733; font-weight:bold;">■</span> Environmental Issues</div>
        <div><span style="color:#DDAA33; font-weight:bold;">■</span> Construction & Infrastructure</div>
        <div><span style="color:#CC3311; font-weight:bold;">■</span> Public Safety</div>
        <div><span style="color:#AA3377; font-weight:bold;">■</span> City Services & Administrative</div>
        <div><span style="color:#0077BB; font-weight:bold;">■</span> Transportation & Street Ops</div>
        <div><span style="color:#332288; font-weight:bold;">■</span> Utilities</div>
    </div>
  </div>

  <!-- Area Legend -->
  <div style="
      background:white;
      padding:10px 14px;
      border:1px solid #ccc;
      border-radius:8px;
      font-size:13px;
      box-shadow:0 2px 6px rgba(0,0,0,0.15);
  ">
    <b>Area Categories</b><br>
    <div style="margin-top:6px;">
        <div><span style="color:#0077BB; font-weight:bold;">■</span> Out of Area</div>
        <div><span style="color:#CC3311; font-weight:bold;">■</span> Industrial</div>
        <div><span style="color:#332288; font-weight:bold;">■</span> Downtown / IU Campus</div>
        <div><span style="color:#EE7733; font-weight:bold;">■</span> Residential</div>
        <div><span style="color:#AA3377; font-weight:bold;">■</span> Suburban Towns</div>
        <div><span style="color:#DDCC77; font-weight:bold;">■</span> Rural Towns</div>
    </div>
  </div>
</div>
"""

# --- Inject legends before </body> ---
html_content = html_content.replace(
    "</body>",
    legends_html + "</body>"
)

# --- Save Edited HTML ---
with open(output_html, "w", encoding="utf-8") as f:
    f.write(html_content)

print("Legends added successfully! Saved as:", output_html)

Legends added successfully! Saved as: project_file_edited.html